### ISSUE TITLE
Diagram and text disagree Re: GH accounts

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/learn-expert-learn-ide-workflow#2]
Diagram and text disagree on github account creation timeline.  In the diagram, it specifically says "not create github" with the Welcome To Learn track, but instead says "GitHub account linked/created at first lab".  However, the text describing the flow states, "User signs up for Learn, first creating a GitHub account".

My suspicion is that it should read "User signs up for Learn, creating an account based on email/password alone".  But I can't be sure.

The text also disagrees with itself in steps 1 and 9.  Step 1: "first creating a GitHub account", step 9: "the student connects/creates their github account ".

**Comment by aturkewi** [comment]
Fixed by PR #4 

Thanks!
